issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    - dupl
    - forbidigo
    - godot
    - exhaustivestruct
    - deadcode
    - errorlint
    - lll
    - unused
    - gofumpt
    - exhaustruct
    - funlen
    - gomnd
    - cyclop
    - gomoddirectives
  # enable:
  #   - gofmt
  #   - gosimple

run:
  timeout: 10m
  go: 1.19

output:
  format: json
  sort-results: true

linters-settings:
  varnamelen:
    ignore-names:
      - k
      - v
      - i
      - x
      - z
