# --------------------------------------------
#
# Standard recommended semantic-release configuration.
#
# Alternative configurations
#  - A .releaserc file, written in YAML or JSON, with optional extensions: .yaml/.yml/.json/.js
#  - A release.config.js file that exports an object
#  - A release key in the project's package.json file
#  Source: https://semantic-release.gitbook.io/semantic-release/usage/configuration#configuration-file
#
#----------------------------------------------

---
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/github"
    - assets:
        - CHANGELOG.md
        - tests/*
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"